### ISSUE TITLE
Change unit tests formats

### ISSUE THREAD

**Issue by cmaneu** [cmaneu/loghash-spec#3]
Use a YAML file that, then generate JSON file.
Sample: 

```
- input: Hello #world
- output:
  - items:
    - hashtags:
      - world
    - identifiers
  - tokens:
      - type: string
        content: Hello
      - type: hashtag
        content: world
```

output: 

```
{
    "input": "Hello"
  }, 
  {
    "output": [
      {
        "items": [
          {
            "hashtags": [
              "world"
            ]
          }, 
          "identifiers"
        ]
      }, 
      {
        "tokens": [
          {
            "content": "Hello", 
            "type": "string"
          }, 
          {
            "content": "world", 
            "type": "hashtag"
          }
        ]
      }
    ]
  }
```
